# Generated by Django 4.0.5 on 2022-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_telephones_telephone_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_card_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_card_scan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
