# Generated by Django 4.0.5 on 2022-06-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_id_card_number_person_id_card_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.person'),
        ),
    ]
