# Generated by Django 4.0.5 on 2022-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_person_telephones_client'),
        ('services', '0002_alter_servicelocation_max_przepustowosc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contracts',
            new_name='Contract',
        ),
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
