# Generated by Django 4.0.5 on 2022-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_contracts_contract_rename_offers_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
