# Generated by Django 4.0.5 on 2022-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
