# Generated by Django 4.0.4 on 2022-06-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_offer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='client',
        ),
    ]
